src/app/app.scss
src/app/components/molecules/header/Header.test.tsx
src/app/components/molecules/header/header.module.scss
src/app/components/molecules/header/header.tsx
src/app/content/content.ts
src/app/layout.tsx
src/app/utils/concatClassNames.ts

CCM-5179: Added additional style to header component

---

.github/CODEOWNERS
docs/testing/index.md

Added code owners and test team

Add code owners and testers folders.

---

src/__tests__/components/NHSNotifyRadioButtonForm.test.tsx
src/__tests__/components/__snapshots__/NHSNotifyRadioButtonForm.test.tsx.snap
src/__tests__/pages/__snapshots__/ChooseTemplate.test.tsx.snap
src/components/forms/ChooseTemplate/ChooseTemplate.tsx
src/components/molecules/Header/Header.tsx
src/components/molecules/NHSNotifyRadioButtonForm/NHSNotifyRadioButtonForm.tsx
src/content/content.ts

- Adds 'Notify' to header
- Adds hint text to choose your template radio fieldset
---

CCM-5960: Snagging list - Update header and hint text on radios

---

.eslintrc.json
.github/workflows/cicd-deploy-amplify-app.yaml
.github/workflows/stage-1-commit.yaml

- updates role-to-assume to use secrets
- foxes linting error
---

CCM-4911: update role to assume to use secrets

---

package-lock.json
package.json

CCM-6251: update dependencies

---

package-lock.json
package.json
src/__tests__/app/choose-a-template-type/__snapshots__/page.test.tsx.snap
src/__tests__/app/choose-a-template-type/page.test.tsx
src/__tests__/app/create-nhs-app-template/page.test.tsx
src/__tests__/app/invalid-session/__snapshots__/page.test.tsx.snap
src/__tests__/app/invalid-session/page.test.tsx
src/__tests__/app/preview-nhs-app-template/page.test.tsx
src/__tests__/utils/form-actions.test.ts
src/__tests__/utils/logger.test.ts
src/app/choose-a-template-type/[sessionId]/page.tsx
src/app/create-nhs-app-template/[sessionId]/page.tsx
src/app/invalid-session/page.tsx
src/app/preview-nhs-app-template/[sessionId]/page.tsx
src/content/content.ts
src/utils/form-actions.ts
src/utils/logger.ts
tests/accessibility/.pa11y-ci.js

CCM-6212: invalid session id handling

---

infrastructure/terraform/components/branch/module_amplify_branch.tf

Enable autbuild on branches
---

CCM-6413 enable feature auto build

---

.github/workflows/manual-combine-dependabot-prs.yaml

adding a workflow to combine all outstanding dependabot PRs on a repository
---

Adding github workflow to combine dependabot PRs

---

tests/performance-test/README.md
tests/performance-test/create_nhsapp_template.py
tests/performance-test/pyproject.toml
tests/performance-test/run.sh
tests/performance-test/shared.py

First performance test script in Locust
First performance test script to create and submit a new template for NHSApp channel
This is to include performance tests for the journeys
---

CCM-6246 : first perf test script

---

src/__tests__/app/invalid-session/page.test.tsx
src/__tests__/app/invalid-template/__snapshots__/page.test.tsx.snap
src/__tests__/app/invalid-template/page.test.tsx
src/__tests__/app/nhs-app-template-submitted/__snapshots__/page.test.tsx.snap
src/__tests__/app/nhs-app-template-submitted/page.test.tsx
src/__tests__/app/submit-nhs-app-template/page.test.tsx
src/__tests__/components/molecules/404.test.tsx
src/__tests__/components/molecules/__snapshots__/404.test.tsx.snap
src/__tests__/domain/templates/template-validator.test.ts
src/__tests__/utils/form-actions.test.ts
src/app/invalid-session/page.tsx
src/app/invalid-template/page.tsx
src/app/nhs-app-template-submitted/[templateId]/page.tsx
src/components/molecules/404/404.tsx
src/components/molecules/TemplateSubmitted/TemplateSubmitted.tsx
src/content/content.ts
src/domain/templates/index.ts
src/domain/templates/template-mapper.ts
src/domain/templates/template-validator.ts
src/domain/templates/templates.types.ts
src/styles/app.scss
src/utils/form-actions.ts
src/utils/types.ts

PR to add UI for the nhs-app-template-submitted page
---

CCM-5523: Template Submitted Page

---

.eslintrc.json
amplify/backend.ts
amplify/data/resource.ts
infrastructure/terraform/components/branch/module_amplify_branch.tf
next.config.js
package-lock.json
src/__tests__/app/choose-a-template-type/__snapshots__/page.test.tsx.snap
src/__tests__/app/choose-a-template-type/page.test.tsx
src/__tests__/app/create-nhs-app-template/page.test.tsx
src/__tests__/app/preview-nhs-app-template/__snapshots__/page.test.tsx.snap
src/__tests__/app/preview-nhs-app-template/page.test.tsx
src/__tests__/components/forms/ChooseTemplate/ChooseTemplate.test.tsx
src/__tests__/components/forms/ChooseTemplate/__snapshots__/ChooseTemplate.test.tsx.snap
src/__tests__/components/forms/ReviewEmailTemplate/__snapshots__/ReviewEmailTemplate.test.tsx.snap
src/__tests__/components/forms/ReviewLetterTemplate/__snapshots__/ReviewLetterTemplate.test.tsx.snap
src/__tests__/components/forms/ReviewNHSAppTemplate/__snapshots__/ReviewNHSAppTemplate.test.tsx.snap
src/__tests__/components/forms/ReviewSMSTemplate/__snapshots__/ReviewSMSTemplate.test.tsx.snap
src/__tests__/components/molecules/__snapshots__/NHSNotifyRadioButtonForm.test.tsx.snap
src/__tests__/components/organisms/__snapshots__/ReviewTemplate.test.tsx.snap
src/__tests__/helpers.ts
src/__tests__/utils/amplify-utils.test.ts
src/__tests__/utils/form-actions.test.ts
src/components/molecules/Footer/Footer.tsx
src/utils/amplify-utils.ts
src/utils/form-actions.ts

PR to add a TTL to the session storage table
---

CCM-5922: Session data TTL

---

next.config.js

CCM-6723: Allow requests from web-gateway origin

---

src/__tests__/components/forms/SubmitTemplate/server-action.test.ts
src/__tests__/utils/form-actions.test.ts
src/components/forms/SubmitTemplate/server-action.ts
src/utils/form-actions.ts

- deletes user session once template has been submitted
---

CCM-5926: delete session when template submitted

---

.github/workflows/stage-2-test.yaml
.github/workflows/stage-4-acceptance.yaml
.gitignore
.tool-versions
amplify/data/resource.ts
amplify/functions/send-email/resource.ts
infrastructure/terraform/components/app/amplify_app.tf
jest.config.ts
package-lock.json
package.json
src/utils/amplify-utils.ts
tests/test-team/README.md
tests/test-team/config/local.config.ts
tests/test-team/config/playwright.config.ts
tests/test-team/helpers/session-storage-helper.ts
tests/test-team/helpers/types.ts
tests/test-team/package-lock.json
tests/test-team/package.json
tests/test-team/pages/template-mgmt-base-page.ts
tests/test-team/pages/template-mgmt-choose-page.ts
tests/test-team/pages/template-mgmt-create-page.ts
tests/test-team/pages/template-mgmt-preview-page.ts
tests/test-team/pages/template-mgmt-start-page.ts
tests/test-team/template-mgmt-component-tests/template-mgmt-choose-page.component.ts
tests/test-team/template-mgmt-component-tests/template-mgmt-create-page.component.ts
tests/test-team/template-mgmt-component-tests/template-mgmt-preview-page.component.ts
tests/test-team/template-mgmt-component-tests/template-mgmt-start-page.component.ts
tests/test-team/template-mgmt-e2e-tests/template-mgmt-nhsapp.e2e.spec.ts

Create initial framework for running automated UI component tests:
- Set up playwright dependencies
- Create initial config to allow local running of tests
- Create setup / teardown of session data to allow seeding of data in Amplifly dynamoDB
- Create Page Object Models for initial components (pages)
- Create initial tests for components (pages)
- Integrate UI component tests into CI/CD Github workflow
- Output test report as artefact with screenshots (on failure) from CI/CD Github workflow
To automate UI testing and minimise manual test effor
---
To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-sa …

CCM-6319: initial framework, pipeline job and tests

---

scripts/config/sonar-scanner.properties

Adjusting sonar properties file.
By setting these properties  we get a better analysis of code in sonar as test code is distinguished from function code and excluded from code coverage analysis. 
---

CCM-6476 -  adjusting sonar properties 

---

.github/workflows/pr_create_dynamic_env.yaml
.github/workflows/pr_merge.yaml
.github/workflows/release_created.yaml
.github/workflows/trigger_internal_repo_build.yaml
infrastructure/terraform/.gitignore
infrastructure/terraform/components/app/route53_record_root.tf

- Adds --fail flag so when invocations of internal repo pipelines fail feedback is faster
- Adds mechanism for deployment on release creation
- Improves deployment to main environment on merge to main branch
- PR merge and release trigger now share a common reusable workflow
- Adds lifecycle to DNS records Amplify is going to manage
---
To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-the-public) or any other sensitive data in this PR (Pull Request) and the codebase changes. We will remove any PR that do contain any sensitive information. We really appreciate your cooperation …

CCM-7035 Adding auto deploy on release

---

tests/test-team/pages/template-mgmt-base-page.ts
tests/test-team/pages/template-mgmt-choose-page.ts
tests/test-team/template-mgmt-component-tests/template-mgmt-choose-page.component.ts
tests/test-team/template-mgmt-component-tests/template-mgmt-common.steps.ts

Adding component ui tests for the "choose-a-template-type" page.
Increases automated test coverage
---

CCM-6321: adding tests for choose type page

---

src/app/submit-nhs-app-template/[sessionId]/page.tsx
tests/test-team/helpers/session-factory.ts
tests/test-team/template-mgmt-component-tests/template-mgmt-submit-page.component.ts
tests/test-team/template-mgmt-component-tests/template-mgmt-submitted-page.component.ts

PR to add tests for NHS App submit-template and template-submitted pages
---

CCM-7083: Add NHS App to submit template and template submitted tests

---

jest.config.ts

- use babel coverage reporter rather than v8
- downside to babel is that it's _ever_ so slightly slower, but seems more reliable
- I also tried SWC to see if any improvements were made, the coverage reporter still failed but the tests were ever so slightly faster
- I ran `npm run test:unit -- --detectOpenHandles --no-cache` multiple times with babel and had no coverage failures. Whereas with v8 the coverage report would fail 80% of the time. 
V8 appears to have active bug against https://github.com/jestjs/jest/issues/14766
---
To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-the …

CCM-7464: try babel coverage reporter

---

infrastructure/terraform/components/acct/iam_policy_github_deploy_overload.tf
infrastructure/terraform/modules/lambda-function/lambda_function_main.tf
infrastructure/terraform/modules/lambda-function/outputs.tf
infrastructure/terraform/modules/lambda-function/variables.tf
infrastructure/terraform/modules/templates-api/dynamodb_table_templates.tf
infrastructure/terraform/modules/templates-api/kms_key_dynamo.tf
infrastructure/terraform/modules/templates-api/module_authorizer_lambda.tf
infrastructure/terraform/modules/templates-api/module_endpoint_lambda.tf
infrastructure/terraform/modules/typescript-build-zip/null_resource_typescript_build.tf
jest.config.ts
lambdas/endpoint/package-lock.json
lambdas/endpoint/package.json
lambdas/endpoint/src/__tests__/index.test.ts
lambdas/endpoint/src/index.ts

Terraform changes to enable database operations to be added to templates API
---

CCM-7252: Terraform changes for implementing database operations in templates API

---

.github/workflows/pr_destroy_dynamic_env.yaml

Destroy environment workflow
---

CCM-8071 destroy env fixes

---

infrastructure/terraform/components/app/ssm_parameter_amplify_password.tf
infrastructure/terraform/components/app/variables.tf

Github Environment vars can only be uppercase
---

CCM-7908 case fixing tfvars

---

frontend/src/__tests__/components/molecules/__snapshots__/TemplateSubmitted.test.tsx.snap
frontend/src/components/molecules/TemplateSubmitted/TemplateSubmitted.tsx
frontend/src/content/content.ts
tests/test-team/template-mgmt-component-tests/template-mgmt-submitted-page.component.ts

Removes link from page after submitting template
---

CCM-7568: Remove new template link from submitted page

---

infrastructure/terraform/components/app/amplify_app.tf

Enables branch auto disconnection on the amplify app.
Enabling allows AWS to remove the branch's amplify app. This stops resources being left behind, which costs money and causes AWS limits to be reached.
Comprehensive test evidence has been added to the [CCM-7001](https://nhsd-jira.digital.nhs.uk/browse/CCM-7001) jira ticket.
---
To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-the-public) or any other sensitive data in this PR (Pull Request) and the codebase changes. We will remove any PR that do contain any sensitive information. We really appreciate your cooperation in this …

CCM-7001 amplify app enable branch auto disconnection

---

frontend/src/__tests__/app/choose-a-template-type/__snapshots__/page.test.tsx.snap
frontend/src/__tests__/components/forms/ChooseTemplate/__snapshots__/ChooseTemplate.test.tsx.snap
frontend/src/__tests__/components/forms/EmailTemplateForm/EmailTemplateForm.test.tsx
frontend/src/__tests__/components/forms/EmailTemplateForm/__snapshots__/EmailTemplateForm.test.tsx.snap
frontend/src/__tests__/components/forms/NhsAppTemplateForm/NhsAppTemplateForm.test.tsx
frontend/src/__tests__/components/forms/NhsAppTemplateForm/__snapshots__/NhsAppTemplateForm.test.tsx.snap
frontend/src/__tests__/components/forms/SmsTemplateForm/SmsTemplateForm.test.tsx
frontend/src/__tests__/components/forms/SmsTemplateForm/__snapshots__/SmsTemplateForm.test.tsx.snap
frontend/src/__tests__/components/molecules/__snapshots__/TemplateSubmitted.test.tsx.snap
frontend/src/components/forms/ChooseTemplate/ChooseTemplate.tsx
frontend/src/components/forms/EmailTemplateForm/EmailTemplateForm.tsx
frontend/src/components/forms/NhsAppTemplateForm/NhsAppTemplateForm.tsx
frontend/src/components/forms/SmsTemplateForm/SmsTemplateForm.tsx
frontend/src/components/molecules/TemplateSubmitted/TemplateSubmitted.tsx
frontend/src/content/content.ts
tests/test-team/pages/email/template-mgmt-create-email-page.ts
tests/test-team/pages/nhs-app/template-mgmt-create-nhs-app-page.ts
tests/test-team/pages/sms/template-mgmt-create-sms-page.ts
tests/test-team/pages/template-mgmt-template-submitted-page.ts
tests/test-team/template-mgmt-component-tests/email/template-mgmt-create-email-page.component.ts
tests/test-team/template-mgmt-component-tests/nhs-app/template-mgmt-create-nhs-app-template-page.component.ts
tests/test-team/template-mgmt-component-tests/sms/template-mgmt-create-sms-page.component.ts
tests/test-team/template-mgmt-component-tests/template-mgmt-submitted-page.component.ts

- Update back links text on choose template type, create and preview template pages (all channels)
- Edit template pages do not have back links
---

CCM-7565: update back links

---

frontend/src/__tests__/app/create-and-submit-templates/__snapshots__/page.test.tsx.snap
frontend/src/__tests__/app/create-and-submit-templates/page.test.tsx
frontend/src/content/content.ts

Update the landing page text in response to changes in the application's functionality.
The application's functionality has changed during development and the text is no longer accurate.
Test evidence added to the ticket [CCM-8404](https://nhsd-jira.digital.nhs.uk/browse/CCM-8404)
---

CCM-8404 Update landing page text

---

infrastructure/terraform/modules/backend-api/dynamodb_table_templates.tf

Adds a lifecycle policy for the table name to prevent issues during a recovery event
---

CCM-7890 fix table recovery name

---

infrastructure/terraform/components/acct/api_gateway_account_global.tf
infrastructure/terraform/components/acct/iam_role_apigateway_logging.tf

Add API Gateway account settings. We are already doing this manually in templates-dev, this is to make it terraform-managed.
---

CCM-8433: Add API Gateway account settings

---

infrastructure/terraform/components/acct/iam_policy_github_deploy_overload.tf

Fixing CI role permissions to AWS backup
---

CCM-8501 backup permissions

---

.github/workflows/pr_merge.yaml

Performs and enforces a check to ensure that only PR's that are merged to main trigger the deployment to main.
Prevents unnecessary deployment pipelines being triggered.
---

CCM-8044: Only Deploy on Merge

---

.github/workflows/pr_closed.yaml

CCM-8044: Only Deploy on Merge - Fix workflow dispatch

---

infrastructure/terraform/components/acct/iam_policy_github_deploy_overload.tf
infrastructure/terraform/components/app/module_eventpub.tf

CCM-7938 messaging infra fixes

---

infrastructure/terraform/components/acct/iam_policy_github_deploy_overload.tf

IAM Deployment role addition of SQS
---

CCM-7938 Deploy role fixes

---

infrastructure/terraform/components/app/module_eventpub.tf

Backing out the eventpub module as for some reason its not working in nonprod
---

CCM-7938 Backout Eventpub module as a temporary measure 

---

infrastructure/terraform/components/app/module_eventpub.tf

destruction also failed because the archive couldnt now be un-created 🤦 
fix found https://github.com/hashicorp/terraform-provider-archive/issues/39 applied to the shared module and increases the tag
---

CCM-8566 Archive Creation Fix

---

infrastructure/terraform/components/acct/iam_role_grafana_access.tf
infrastructure/terraform/components/acct/variables.tf

IAM Role for Grafana access from Observability account.
---

CCM-8202: Grafana Cross Account Access

---

.github/workflows/stage-2-test.yaml
.github/workflows/stage-4-acceptance.yaml
frontend/.env.template
frontend/jest.setup.ts
scripts/create-env-file.ts
scripts/tests/accessibility.sh
tests/test-team/config/component/component.config.ts

remove dependency on manually editing the `.env` file as it gets overwritten when running `npm run build`.
Also removed setting `INCLUDE_AUTH_PAGES` in workflows, since it's already being set in Playwright setup (and now also in the accessibility test setup script - setting it here seems better so it works locally)
---

CCM-8580: letter feature flag env var fixes

---

infrastructure/terraform/components/acct/README.md
infrastructure/terraform/components/acct/variables.tf
infrastructure/terraform/components/app/README.md
infrastructure/terraform/components/app/iam_role_grafana_access.tf
infrastructure/terraform/components/app/module_nhse_backup_vault.tf
infrastructure/terraform/components/app/variables.tf
infrastructure/terraform/modules/backend-api/README.md

Renaming Grafana IAM role for consistency
---

CCM-8742: grafana iam role

---

.github/workflows/cicd-1-pull-request.yaml
infrastructure/terraform/components/app/iam_role_amplify.tf
infrastructure/terraform/modules/backend-api/iam_role_api_gateway_execution_role.tf
infrastructure/terraform/modules/lambda-function/iam_role_lambda_execution_role.tf

- Fixes a whitespace detection bug in the CICD1 workflow step
- Switch IAM roles with inline policies to using named policies with role attachements
From the recent Pen test
> Several IAM roles were found with inline policies embedded directly within them. Inline policies are
harder to audit, manage, and enforce consistently across multiple roles. Unlike managed policies,
inline policies cannot be reused, making policy maintenance more complex and increasing the risk
of privilege misconfiguration. Best practices recommend migrating inline policies to AWS managed
or customer-managed policies to improve security visibility and access control
---
To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable …

CCM-8752 Replace inline policies with attached policies

---

infrastructure/terraform/components/acct/README.md
infrastructure/terraform/components/acct/module_s3bucket_access_logs.tf

Adding S3 Access logging bucket and setting other buckets to use it
---

CCM-8840 Adding S3 Access Logging

---

infrastructure/terraform/components/acct/iam_policy_github_deploy_overload.tf

Add AWS Pipes permissions to deployment policy
Allows us to deploy AWS Pipe resources. This is acct level change to putting into a separate PR to stop it being overwritten and hindering development. 
---

CCM-8572: add pipes permission to deploy policy

---

frontend/next.config.js

CCM-8985: Fix allowedOrigins

---

.github/workflows/pr_destroy_dynamic_env.yaml

Fixes error on PR sandbox destruction
---

CCM-9045: Fix PR env destroy

---

frontend/src/__tests__/components/forms/LetterTemplateForm.test.tsx/__snapshots__/LetterTemplateForm.test.tsx.snap
frontend/src/components/atoms/FileUpload/FileUpload.tsx
frontend/src/components/forms/LetterTemplateForm/LetterTemplateForm.tsx

- Adds missing spacing between form groups
- Adds missing padding on form groups
- Fixes missing font weight on form labels
- The spacing between field sections on the page is not as per the design
- The field labels for 'Letter type' and 'Additional language' do not have the correct font weight to match the other field labels on the same page
---
To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-the-public) or any other sensitive data in this PR (Pull Request) and the codebase changes. We will remove any PR that do contain any sensitive information. We really appreciate your …

CCM 9212 Fix styling on letter template

---

frontend/src/__tests__/components/molecules/Header.test.tsx
frontend/src/__tests__/components/molecules/__snapshots__/Header.test.tsx.snap
frontend/src/components/molecules/Header/Header.tsx
frontend/src/content/content.ts

- Updates aria-label on logo link
- Adds <title> to inline SVG for logo
- Improves accessibility of the logo link
---

CCM-8859 Update accessibility text for logo

---

infrastructure/terraform/components/acct/README.md
infrastructure/terraform/components/acct/outputs.tf

CCM-9140 rename vpc output

---

infrastructure/terraform/components/acct/README.md
infrastructure/terraform/components/acct/outputs.tf

Fixes missing output from acct module leading to failed app deployments that relied on it.
---

CCM-8197: Cross Account Observability_v2

---

infrastructure/terraform/components/sandbox/README.md
infrastructure/terraform/components/sandbox/outputs.tf
infrastructure/terraform/modules/backend-api/README.md
infrastructure/terraform/modules/backend-api/locals.tf
infrastructure/terraform/modules/backend-api/module_lambda_process_proof.tf
infrastructure/terraform/modules/backend-api/outputs.tf
lambdas/backend-api/src/__tests__/templates/api/process-proof.test.ts
lambdas/backend-api/src/__tests__/templates/infra/letter-file-repository.test.ts
lambdas/backend-api/src/__tests__/templates/infra/letter-upload-repository.test.ts
lambdas/backend-api/src/templates/api/process-proof.ts
lambdas/backend-api/src/templates/container.ts
lambdas/backend-api/src/templates/infra/config.ts
lambdas/backend-api/src/templates/infra/letter-file-repository.ts
lambdas/backend-api/src/templates/infra/letter-proof-repository.ts
tests/test-team/global.d.ts
tests/test-team/helpers/db/template-storage-helper.ts
tests/test-team/template-mgmt-e2e-tests/template-mgmt-proofing.e2e.spec.ts
utils/backend-config/src/backend-config.ts

PR to copy files to download bucket if there's a successful virus scan
---

CCM-9872: Copy file to download bucket

---

infrastructure/terraform/components/acct/sns_topic_costs.tf

CCM-10036 CostAnomalyAlarms fix

---

infrastructure/terraform/components/app/README.md
infrastructure/terraform/components/app/cloudwatch_log_group_amplify.tf
infrastructure/terraform/components/app/locals.tf
infrastructure/terraform/components/app/module_backend_api.tf
infrastructure/terraform/components/app/variables.tf

Lambda log destination fix for nonprod envs, pointing to log destination in sharedinfra
---

CCM-11007: Lambda log destination fix

---

infrastructure/terraform/components/acct/module_ses_testing.tf

Avoid creating SES testing module on nonprod, where there is no account level KMS key
---

CCM-10282: SES testing module fix for nonprod

---

frontend/src/__tests__/components/forms/LetterTemplateForm.test.tsx/__snapshots__/LetterTemplateForm.test.tsx.snap
frontend/src/__tests__/components/molecules/__snapshots__/PreviewTemplateDetails.test.tsx.snap
frontend/src/__tests__/components/organisms/__snapshots__/PreviewLetterTemplate.test.tsx.snap
frontend/src/components/molecules/PreviewTemplateDetails/PreviewTemplateDetailsLetter.tsx
frontend/src/content/content.ts
lambdas/sftp-letters/src/__tests__/domain/test-data.test.ts
lambdas/sftp-letters/src/app/request-proof.ts
lambdas/sftp-letters/src/domain/test-data.ts
tests/test-team/template-mgmt-component-tests/letter/template-mgmt-create-letter-template-page.component.spec.ts

- Updates content to be "example personalisation data" rather than "test personalisation data"
- Updates snapshots
- Updates naming in lambdas for consistency
Terminology between the Notify website and the Web UI is misaligned when it comes to the example personalisation data file, needs updating to avoid confusion
---

[CCM-10141] Update personalisation data copy

---

infrastructure/terraform/components/app/README.md
infrastructure/terraform/components/app/locals.tf
infrastructure/terraform/components/app/module_backend_api.tf
infrastructure/terraform/components/app/variables.tf

Tfvar changes to cutover BCs to Observability in SharedInfra account for Production
---

CCM-10579: Observability Prod Cutover

---

infrastructure/terraform/components/acct/locals.tf

Eventbus arn proj name fix
---

CCM-11363: Eventbus arn

---

.github/workflows/dispatch_internal_repo_workflow.yaml

- Adds a caller run ID to all test workflows and uses it to filter them when polling to match the correct workflow URL
- Adds a path filter which will apply to all internal workflows to make the matching more robust
---

CCM-11726 Add run ID to trigger and filter

---

infrastructure/terraform/modules/backend-api/dynamodb_table_routing_configuration.tf

Adds table with TTL and an index on 'id' intended to help with manual checks.
---

CCM-11162: routing config table

---

lambdas/backend-client/src/__tests__/schemas/template-schema.test.ts
lambdas/backend-client/src/schemas/constants.ts
lambdas/backend-client/src/schemas/template-schema.ts
tests/test-team/template-mgmt-api-tests/create-template.api.spec.ts
tests/test-team/template-mgmt-api-tests/update-template.api.spec.ts

CCM-10931: Remove app forbidden character regex

---

infrastructure/terraform/components/app/README.md
infrastructure/terraform/components/app/module_eventpub.tf
infrastructure/terraform/components/sandbox/README.md
infrastructure/terraform/components/sandbox/module_eventpub.tf

CCM-11751: Fixing eventpub path

---

frontend/src/__tests__/components/forms/PreviewEmailTemplate/__snapshots__/PreviewEmailTemplate.test.tsx.snap
frontend/src/__tests__/components/forms/PreviewNHSAppTemplate/__snapshots__/PreviewNHSAppTemplate.test.tsx.snap
frontend/src/__tests__/components/forms/PreviewSMSTemplate/__snapshots__/PreviewSMSTemplate.test.tsx.snap
frontend/src/__tests__/components/molecules/MessageTemplates.test.tsx
frontend/src/__tests__/components/molecules/PreviewTemplateDetails.test.tsx
frontend/src/__tests__/components/molecules/__snapshots__/MessageTemplates.test.tsx.snap
frontend/src/__tests__/components/molecules/__snapshots__/PreviewTemplateDetails.test.tsx.snap
frontend/src/components/molecules/MessageTemplates/MessageTemplates.tsx
frontend/src/components/molecules/PreviewTemplateDetails/common.tsx
package-lock.json
tests/test-team/template-mgmt-component-tests/template-mgmt-copy-page.component.spec.ts
tests/test-team/template-mgmt-component-tests/template-mgmt-message-templates-page.component.spec.ts
utils/utils/src/__tests__/enum.test.ts
utils/utils/src/enum.ts

- changes Not yet submitted to Draft in the UI for digital only channels
---

CCM-11457: change Not yet submitted to Draft in the UI for digital channels

---

.github/workflows/stage-1-commit.yaml
infrastructure/terraform/components/app/README.md
infrastructure/terraform/components/app/module_nhse_backup_vault.tf
infrastructure/terraform/components/app/variables.tf

Setting retention period of backup recovery points to 31 days as per NHSE guidelines
---

CCM-12082: Setting retention period of backup recovery points to 31 days as per NHSE guidelines
